<?php

namespace Container6gEwx9N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\TournamentService' shared autowired service.
     *
     * @return \App\Services\TournamentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'TournamentService.php';

        return $container->privates['App\\Services\\TournamentService'] = new \App\Services\TournamentService(($container->privates['App\\Repository\\TournamentRepository'] ?? $container->load('getTournamentRepositoryService')));
    }
}
