<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6gEwx9N\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6gEwx9N/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6gEwx9N.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6gEwx9N\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container6gEwx9N\App_KernelTestDebugContainer([
    'container.build_hash' => '6gEwx9N',
    'container.build_id' => '216eb689',
    'container.build_time' => 1635517837,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6gEwx9N');
