<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'participant' => [[], ['_controller' => 'App\\Controller\\ParticipantController::index'], [], [['text', '/participant']], [], []],
    'ping' => [[], ['_controller' => 'App\\Controller\\PingController::index'], [], [['text', '/api/ping']], [], []],
    'create_tournament' => [[], ['_controller' => 'App\\Controller\\TournamentController::addTournament'], [], [['text', '/api/tournaments']], [], []],
    'get_tournament' => [['id'], ['_controller' => 'App\\Controller\\TournamentController::getTournament'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/tournaments']], [], []],
    'add_participant_to_tournament' => [['tournamentId'], ['_controller' => 'App\\Controller\\TournamentController::addParticipantToTournament'], [], [['text', '/participants'], ['variable', '/', '[^/]++', 'tournamentId', true], ['text', '/api/tournaments']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
];
